version: "3.9"
services:
    project:
        build: .
        container_name: project
        stdin_open: true
        tty: true
        command: bash
        gpus: all
        working_dir: /app
        volumes:
            - .:/app